name: Rodar Python e gerar HTML

on:
  workflow_dispatch:

jobs:
  gerar-html:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do repositório
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Rodar arquivo Python
        run: |
          python gerar_apresentacao.py

      - name: Mostrar arquivos gerados
        run: |
          ls -lh

      - name: Salvar HTML gerado para download
        uses: actions/upload-artifact@v4
        with:
          name: apresentacao-html
          path: quintal-barigui-investidores-FINAL.html
          if-no-files-found: error
